// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { proxy } from "../models";

export function GetProxyAddr(): Promise<string>;

export function GetRewriteRules(): Promise<Array<profiles.RewriteRule>>;

export function SetRewriteRules(
  arg1: Array<profiles.RewriteRule>,
): Promise<void>;
